<?php

namespace AppBundle\Repository;

/**
 * AyFuncionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AyFuncionRepository extends \Doctrine\ORM\EntityRepository
{
}
