<?php

namespace AppBundle\Repository;

/**
 * AyGrupoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AyGrupoRepository extends \Doctrine\ORM\EntityRepository
{
}
