<?php

namespace AppBundle\Repository;

/**
 * AyModuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AyModuloRepository extends \Doctrine\ORM\EntityRepository
{
}
