<?php

namespace AppBundle\Repository;

/**
 * ay_temaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AyTemaRepository extends \Doctrine\ORM\EntityRepository
{
}
