<?php

namespace AppBundle\Repository;

/**
 * ClienteImplementacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteImplementacionRepository extends \Doctrine\ORM\EntityRepository
{
}
