<?php

namespace AppBundle\Repository;

/**
 * ImplementacionConceptoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImplementacionConceptoRepository extends \Doctrine\ORM\EntityRepository
{
}
