<?php

namespace AppBundle\Repository;

/**
 * IncidenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncidenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
