<?php

namespace AppBundle\Repository;

/**
 * IncidenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncidenciaRepository extends \Doctrine\ORM\EntityRepository {

    public function listaDql($strCodigoCliente = "",$strCodigoCategoria = "", $estadoAtendido = "",$idIncidencia ="") {
        $dql = "SELECT i FROM AppBundle:Incidencia i WHERE i.estadoSolucionado = 0";
        if ($strCodigoCliente != "") {
            $dql .= " AND i.codigoClienteFk = " . $strCodigoCliente;
        }
        if ($strCodigoCategoria != "") {
            $dql .= " AND i.codigoCategoriaFk = " . $strCodigoCategoria;
        }
        if ($estadoAtendido != 2 && $estadoAtendido != "") {
            $dql .= " AND i.estadoAtendido = " . $estadoAtendido;
        }
        if ($idIncidencia != 0) {
            $dql .= " AND i.codigoIncidenciaPk = " . $idIncidencia;
        }
        $dql .= " ORDER BY i.fechaRegistro DESC";
        return $dql;
    }

    public function eliminarIncidente($arrSeleccionados) {
        $em = $this->getEntityManager();
        if (count($arrSeleccionados) > 0) {
            foreach ($arrSeleccionados AS $codigoIncidencia) {
                $arIncidencia = $em->getRepository("AppBundle:Incidencia")->find($codigoIncidencia);
                if ($arIncidencia->getEstadoAtendido() == 0) {
                    $arComentario = $em->getRepository("AppBundle:Comentario")->findBy(array('codigoIncidenciaFk' => $codigoIncidencia));
                    if (count($arComentario > 0)) {
                        foreach ($arComentario as $arComentario) {
                            $em->remove($arComentario);
                        }
                    }
                    $em->remove($arIncidencia);
                } else {
                    $mensaje = 'No se puede eliminar el caso despues de atendido';
                }
            }
            $em->flush();
        }
    }

}
