<?php

namespace AppBundle\Repository;

/**
 * LlamadaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LlamadaRepository extends \Doctrine\ORM\EntityRepository
{
    public function listaDql() {
        $dql = "SELECT i FROM AppBundle:Llamada i WHERE i.codigoLlamadaPk <> 0";
        $dql .= " ORDER BY i.codigoLlamadaPk DESC";
        return $dql;
    }
}
