security:
        
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER]

    encoders:
        AppBundle\Entity\User: bcrypt
        
    providers:
        db_users:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            http_basic: ~
            provider: db_users
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout: 
                path: /logout
                target: /login
                
    access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/contacto, roles: ROLE_USER }
    - { path: ^/caso/lista, roles: ROLE_USER }
    - { path: ^/caso/nuevo/, roles: ROLE_USER }
    - { path: ^/caso/editar/, roles: ROLE_USER }
    - { path: ^/caso/detalle/, roles: ROLE_USER }
    - { path: ^/caso/editarAdmin/, roles: ROLE_USER }
    - { path: ^/admin/caso/lista, roles: ROLE_USER }
    - { path: ^/admin/caso/nuevo/, roles: ROLE_USER }
    - { path: ^/admin/caso/editar/, roles: ROLE_USER }
    - { path: ^/admin/caso/detalle/, roles: ROLE_USER }
    - { path: ^/admin/caso/editarAdmin/, roles: ROLE_USER }
    - { path: ^/admin/tarea/lista, roles: ROLE_USER }
    - { path: ^/admin/tarea/nuevo/, roles: ROLE_USER }
    - { path: ^/admin/tarea/detalle/, roles: ROLE_USER }
    - { path: ^/contacto, roles: ROLE_USER }
    - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }